# Generated by Django 4.0.4 on 2022-05-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nuevo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='valor_ofera',
            field=models.IntegerField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
