# Generated by Django 4.0.4 on 2022-05-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_nuevo_producto_oferta_producto_valor_ofera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='valor_ofera',
        ),
        migrations.AddField(
            model_name='producto',
            name='valor_oferTa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
