# Generated by Django 4.0.4 on 2022-05-21 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_valor_oferta_producto_valor_oferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoria', models.CharField(default='NombreSubcategoria', max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='core.subcategoria'),
            preserve_default=False,
        ),
    ]
