# Generated by Django 4.0.4 on 2022-05-21 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subcategoria_alter_producto_nombre_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.PROTECT, to='core.subcategoria'),
        ),
    ]
