# Generated by Django 4.0.4 on 2022-05-21 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_producto_subcategoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategoria',
            old_name='subcategoria',
            new_name='subcategorias',
        ),
        migrations.AlterField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.subcategoria'),
        ),
    ]
