# Generated by Django 4.0.4 on 2022-05-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_subcategoria_subcategoria_subcategorias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategoria',
            old_name='subcategorias',
            new_name='subcategoria',
        ),
    ]
